/*
 * Copyright (C) 2016 Google Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */

package com.google.android.accessibility.switchaccess.menuitems;

import com.google.android.accessibility.switchaccess.proto.SwitchAccessMenuItemEnum;
import com.google.android.accessibility.switchaccess.ui.OverlayController.MenuListener;

/** Holds all data required to construct an item in a Switch Access menu. */
public abstract class MenuItem {

  public abstract int getIconResource();

  public abstract String getText();

  public abstract MenuItemOnClickListener getOnClickListener();

  /** Interface to listen to the selection of an item on the Switch Access menu. */
  public interface SelectMenuItemListener {
    /**
     * Called when a menu item is selected. When {@link MenuListener#onMenuClosed} is called, if the
     * menu Id does not match the last Id of the menu when {@link MenuListener#onMenuShown} is
     * called, all logs generated by onMenuItemSelected during this period will be dropped.
     */
    void onMenuItemSelected(SwitchAccessMenuItemEnum.MenuItem menuItem);
  }
}
