# This package contains stubs for any functionality that requires the
# experimental Android SDK
load("//java/com/google/devtools/staticanalysis/java/checker:build_defs.bzl", "android_library_with_nullness_check")

android_library_with_nullness_check(
    name = "utils",
    size = "medium",
    srcs = glob(["*.java"]),
    visibility = ["//java/com/google/android/accessibility/talkback:__pkg__"],
)
